anbox/anbox

data/anbox.desktop
Since you're going to install the icon to a location compliant with [freedesktop.org standards](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) (I take it that way, otherwise you'd have to specify the full path) you don't need to specify the icon file extension in the `.desktop` launcher. It will be found anyway.
This facilitates the use of non-PNG (e.g. SVG) app icon themes.
Cf. this [example `.desktop` launcher](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#example).
=> Unhardcoded app launcher icon filetype

scripts/snap-wrapper.sh
snap-confine makes the nvidia driver binaries from the host available in /var/lib/snapd/gl. Adding this to LD_LIBRARY_PATH should help a bit to get Anbox working for people using the Nvidia driver.
Fixes https://github.com/anbox/anbox/issues/11
=> Add in-snap path to nvidia driver binaries to LD_LIBRARY_PATH

cmake/FindGMock.cmake
Taken from https://code.launchpad.net/~cmake-extras/cmake-extras/trunk
=> Import helper cmake script to find GMock and GTest on more modern systems

src/anbox/qemu/adb_message_processor.cpp
This will ensure the message processor is correctly terminated and
a new connection is established when the adb server process on the
host opens a connection to us again.
=> Close connection when adbd connection is closed

docs/build-android.md, src/anbox/rpc/connection_creator.cpp
Setting up the build environment is a required step.
Without it, the subsequent step `lunch` will not be available.
Signed-off-by: Lee Jones <lee.jones@linaro.org>
Fixes https://github.com/anbox/anbox/issues/222
=> docs: build-android.md: Add missing step to initialise the build env

external/android-emugl/host/libs/GLESv1_dec/CMakeLists.txt, external/android-emugl/host/libs/GLESv2_dec/CMakeLists.txt, external/android-emugl/host/libs/Translator/GLcommon/CMakeLists.txt, external/android-emugl/host/libs/libOpenGLESDispatch/CMakeLists.txt, external/android-emugl/host/libs/renderControl_dec/CMakeLists.txt, external/android-emugl/shared/OpenglCodecCommon/CMakeLists.txt, external/android-emugl/shared/emugl/common/CMakeLists.txt, external/process-cpp-minimal/src/CMakeLists.txt, external/xdg/CMakeLists.txt, src/CMakeLists.txt
Make sure helper libraries get built as static libs regardless
of the cmake version being used.
This fixes issue #217
Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>
=> Make sure helper libraries get built as static libs

scripts/container-manager.sh, src/anbox/cmds/container_manager.cpp, src/anbox/cmds/container_manager.h
This will tell users what they are doing wrong when they are running the container manager manually like a lot of people do as our bug reports show.
=> Print warning if user starts container manager manually

src/anbox/cmds/session_manager.cpp, src/anbox/cmds/session_manager.h
Normally Anbox will use the default container provided by the
Anbox Container Manager, but some users may wish to run their
own container.  Here we're adding a --use-own-container flag
which tells the session-manager not to interact (configure/
start) the Container Manager.  This allows the user to utilise
any other bespoke container of their choosing.  For instance,
this new feature was testing using Docker container running
the android.img provided by Anbox.
Signed-off-by: Lee Jones <lee.jones@linaro.org>
=> cmds: session_manager: Provide an option to use any container

external/xdg/xdg.cpp, src/anbox/cmds/session_manager.cpp, src/anbox/graphics/emugl/ColorBuffer.cpp, src/anbox/graphics/emugl/TextureDraw.cpp, src/anbox/graphics/emugl/TextureDraw.h, src/anbox/network/published_socket_connector.cpp, src/anbox/network/tcp_socket_connector.cpp, src/anbox/qemu/pipe_connection_creator.cpp, src/anbox/rpc/connection_creator.cpp, src/anbox/runtime.cpp
Fixes building anbox with clang 4.0 -- removes unused declarations,
makes sure a template is visible at first instantiation, makes sure
exception declarations match between headers and implementations
Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>
=> Fix build with clang

src/anbox/cmds/container_manager.cpp, src/anbox/cmds/launch.cpp, src/anbox/container/lxc_container.cpp, src/anbox/logger.cpp, src/anbox/logger.h
With https://github.com/anbox/anbox/pull/251 we started to write out a static IP configuration for the container into /data/misc/ethernet but never changed the permissions of the created directory hierarchy to be owned by our unprivileged user. Because of that services inside the container failed to launch as they couldn't create any files within the same directories.
This PR fixes this by assigning filesystem ownership to our unprivileged user for the relevant directories.
=> Correct permissions for Android IP configuration directory to prevent failing container start

src/anbox/bridge/platform_api_skeleton.h, src/anbox/qemu/at_parser.h
From the Porting to [GCC 7][1] page:
> Several C++ Standard Library headers have been changed to no longer include
> the `<functional>` header. As such, C++ programs that used components defined
> in `<functional>` without explicitly including that header will no longer
> compile.
> Previously components such as std::bind and std::function were
> implicitly defined after including unrelated headers such as `<memory>`,
> `<future>`, `<mutex>`, and `<regex>`.
> Correct code should `#include <functional>` to define them.
[1]: https://gcc.gnu.org/gcc-7/porting_to.html
Signed-off-by: Eddie Ringle <eddie@ringle.io>
=> Fix build with GCC 7.1

kernel/ashmem/dkms.conf, kernel/binder/dkms.conf
The Makefile for ashmem and binder have this line:
KERNEL_SRC ?= /lib/modules/$(shell uname -r)/build
so dkms will always build those modules against running kernel,
even for other kernel version headers. With this commit dkms will
always provide the necessary kernel version.
=> dkms: fix modules build with more kernel versions

snapcraft.yaml
Changes:
* Android system log is now dumped into $ANDROID_DATA/system.log so
it can be accessed without adb and logcat
* Fix SEGV in art on newer kernels with CVE-2017-1000364 fixed
Fixes #337
=> Update to newer Android image

src/anbox/cmds/launch.cpp, src/anbox/cmds/launch.h, src/anbox/cmds/session_manager.cpp, src/anbox/cmds/session_manager.h
This is necessary in some deployments where no session dbus is available.
=> Allow the use of the system dbus service

src/anbox/cmds/container_manager.cpp, src/anbox/common/mount_entry.cpp, src/anbox/common/mount_entry.h, src/anbox/utils.cpp, src/anbox/utils.h
In some environments (containers) we don't have support for loopback devices and therefor the best choice is to use squashfuse. The implementation hands the mount work off to the mount program so we don't have to care about any implementations details of the squashfuse program and leave this entirely up to the existing infrastructure.
The container manager will automatically fallback to use squashfuse when it detects there is no support for loopback devices.
=> Add support for rootfs mounts via squashfuse

kernel/binder/Makefile, kernel/binder/binder.c, kernel/binder/binder.h, kernel/binder/deps.c
This backports the binder driver from the latest upstream linux
kernel tree as of v4.13-rc3-118-g19ec50a43 and enables a working
build on older kernels (e.g. 4.4).
The newer driver allows specification of multiple binder device
nodes but for the moment we only enable the default "binder" one.
Fixes #223
=> binder: update to latest version and fix build on older kernels

snapcraft.yaml
Previously we always load android.img from server when building snap.
Now, build with <ANBOX>/android-images/android.img if there is one.
=> snap build: prefer local android.img rather than always download

src/anbox/cmds/session_manager.cpp
Translator should be rarely used these days. Most environments have a GL ES driver which is enough for our needs around.
=> cmds: select host as the default GL ES driver

external/android-emugl/host/libs/Translator/EGL/EglOsApi_glx.cpp, src/anbox/qemu/adb_message_processor.cpp, src/anbox/qemu/adb_message_processor.h
This PR makes sure that the adb connection can recover after an "adb kill-server" command.
=> Recover on adb server killed

src/anbox/bridge/android_api_stub.cpp, src/anbox/cmds/launch.cpp, src/anbox/cmds/session_manager.cpp, src/anbox/dbus/interface.h, src/anbox/graphics/emugl/Renderer.cpp, src/anbox/logger.cpp, src/anbox/ui/splash_screen.cpp
This improves the session manager startup process quite a lot.  Changes in detail are
* Don't force host GL driver on nvidia platforms anymore; we don't need this as we're using the host GL driver by default now
* Only attempt to create a SDL renderer when we don't have one already; a SDL window attempts to create a renderer on it's own at times so we check for that and only create one when necessary
* Print out example launch intent when executed without any argument: people were confused what kind of arguments to provide to the launch command so we're now giving them an example
* Apply proper daemonization handling for forked session manager: the most important change of this PR. We were lazy in forking of the session manager before and didn't ensured it's properly getting its own …
=> Fix various problems with the session manager startup process

external/android-emugl/shared/emugl/common/lazy_instance.cpp
Small fix required for build to succeed on 64-bit ARM.
=> emugl: Fix build on arm64

src/anbox/qemu/qemud_message_processor.cpp
It is possible for more than one message to be delivered concurrently.
When this happens, messages are concatenated together (end-to-end).
Current code errors out if the total received data is larger than the
known header_size (4) + the body size (reported in the header).
However, when >=2 messages arrive at the same time, the total received
data will be far greater than this.
The current code base actually handles multiple messages perfectly
already, so all we need to do is remove the early return and
everything "just works".
Signed-off-by: Lee Jones <lee.jones@linaro.org>
=> anbox: qemu: qemud_message_processor: Handle multiple 'cat'ed messages

kernel/binder/binder.c
changes the argument for kernel 4.15 and later.
=> kernel specific patch -- fix argument in binder_set_stop_on_user_error

src/anbox/runtime.cpp, src/anbox/runtime.h
add static_cast<int>() on pool_size_ casting to avoid narrowing conversion errors
=> Fix narrowing conversion inside {} (Boost 1.66)

scripts/snap-wrapper.sh
=> scripts: explicitly set linker search path for libpulsecommon-8.0

src/anbox/container/management_api_stub.cpp, src/anbox/container/management_api_stub.h, src/anbox/qemu/adb_message_processor.cpp
If container manager dies before session manager dying,
the session manager cannot exit if it waits for all.
Signed-off-by: Han Pengfei <hanpfei@gmail.com>
=> Just waiting 3 seconds when stop container.

external/android-emugl/host/tools/emugen/ApiGen.cpp, external/process-cpp-minimal/include/core/posix/signal.h, external/process-cpp-minimal/src/core/posix/signal.cpp, src/anbox/cmds/session_manager.cpp, src/anbox/graphics/emugl/RenderThread.cpp
Fix new nir shader memory leaking issue on translator host side, this kind of issue is heavily increasing the memory usage in host side when the application is creating/closing and compiling gles2 nir shader frequently.
=> Fix nir shaders memory leak on translator host side

src/anbox/graphics/emugl/RenderControl.cpp
If we expose too many extensions we don't support ourself yet (like
EGL_ANDROID_native_fence_sync) then we get unexpected corruption or
missing screen updates in our rendered output.
Fixes #635, #457, #692, #582 (and a few more duplicates)
=> emugl: limit set of extensions we expose to Android

snap/snapcraft.yaml
We only support the snap for amd64 at the moment.
=> Limit snap architectures to amd64

snap/snapcraft.yaml
This gives us various fixes needed to get a working graphical experience
with the swiftshader OpenGL ES driver.
=> snap: use the same swiftshader branch as the emugl project does

.gitignore, scripts/container-manager.sh, scripts/snap-wrapper.sh, snap/hooks/configure
Can be enabled via `$ snap set anbox debug.enable=true`. To be effective for the container manager it need to be restarted `$ snap restart anbox.container-manager`
=> Add snap configure hook to allow enable debug mode

external/backtrace-cpp/CMakeLists.txt
=> add -Wno-error=implicit-fallthrough and -Wno-error=switch-default to CMAKE_CXX_FLAGS

src/CMakeLists.txt, src/anbox/cmds/session_manager.cpp, src/anbox/container/configuration.h, src/anbox/container/lxc_container.cpp, src/anbox/container/lxc_container.h, src/anbox/container/management_api_skeleton.cpp, src/anbox/container/management_api_stub.cpp, src/anbox/protobuf/anbox_container.proto, src/anbox/system_configuration.cpp, src/anbox/system_configuration.h
The simple bind mount we used before to forward necessary devices nodes
into the Android container missed shifting the uid/gid. Now we recreate
the devices nodes in a private directory and shift the uid/gid correctly
and then bind mount the resulting files into the container. This should
avoid problems we've have seen on some systems with not allowed access
to some of the device nodes.
Maybe a fix for #741
=> lxc: bind relevant devices nodes into the container with shifted uid/gid

scripts/anbox-init.sh, snap/snapcraft.yaml, src/anbox/container/lxc_container.cpp, src/anbox/container/lxc_container.h
So far we were always mapping the UID of the current user directly into the container to allow the sockets being accessible inside the container. This only works as long as the UID of the current user is 1000 (as this matches the UID of the Android system user). If the UID is different things break. To fix this we now map the id of the current user always to the one of the system user inside the container. This makes all sockets accessible by the relevant Android system components and also lets us keep the sockets owned by the current user.
Things still break if multiple users on the same system try to use Anbox. This needs to be fixed separately as it involves more complex code changes and also migration of existing installations.
=> Map UIDs correctly into the container be independent of the UID initiating the container

snap/snapcraft.yaml
Includes a fix to let the mediaserver not crash because of a not allowed nanosleep syscall.
See https://github.com/anbox/platform_frameworks_av/pull/1
=> Use latest Android image from our build server

docs/install.md
You should say:
"If you haven't logged into the Ubuntu Store yet"
Instead of :
"If you didn't logged into the Ubuntu Store yet"
=> Improper use of "didn't" in install doc file

src/anbox/cmds/container_manager.cpp
kernel document says:
Multiple lower layers can now be given using the the colon (":") as a
separator character between the directory names.  For example:
mount -t overlay overlay -olowerdir=/lower1:/lower2:/lower3 /merged
As the example shows, "upperdir=" and "workdir=" may be omitted.  In
that case the overlay will be read-only.
The specified lower directories will be stacked beginning from the
rightmost one and going left.  In the above example lower1 will be the
top, lower2 the middle and lower3 the bottom layer.
The user directory should be on top, so that user can override the file
in original rootfs image.
=> fix overlay lowerdir order

scripts/snap-wrapper.sh, snap/hooks/install, src/CMakeLists.txt, src/anbox/cmds/check_features.cpp, src/anbox/cmds/check_features.h, src/anbox/cmds/system_info.cpp, src/anbox/daemon.cpp
This will fail the snap installation of any of the features are not supported by the CPU the host system runs on.
=> Check for mandatory CPU features on install

CMakeLists.txt, scripts/container-manager.sh, snap/snapcraft.yaml, src/anbox/container/lxc_container.cpp
This only prepares Anbox to run under full snap confinement. Unless https://github.com/snapcore/snapd/pull/5495 is merged we can't enable full confinement.
=> Initial support for full snap confinement

scripts/anbox-bridge.sh
Can be use like `$ snap set anbox bridge.address=192.168.1.2`
This is only the first half to fix #840. With the config options the bridge configuration can be changed but the network device inside the Android container will still receive the wrong configuration. See https://github.com/anbox/anbox/blob/master/src/anbox/container/lxc_container.cpp#L44 This requires additional changes to change the container configuration according to the bridge configuration.
=> Make network bridge configurable

src/anbox/platform/sdl/platform.cpp
=> sdl: don't prevent screensaver to systems to suspend properly

src/anbox/cmds/check_features.cpp
The cpu_features library doesn't work well enough on QEMU so we skip the
test on any QEMU branded CPU.
=> cmds: ignore cpu feature check on QEMU

CMakeLists.txt, src/anbox/platform/sdl/platform.cpp
It looks like that the Android system gets confused when both a pointer
and an touch based input device are connected to the system. As touch
support is so far only used Ubports we can keep it disabled for the
snap version but provide a configuration switch to enable it again.
=> sdl: disable touch input support by default

src/anbox/application/database.cpp, src/anbox/application/database.h
This keep the desktop icons on anbox bootup until new icons gets added. 
This is mostly for ubuntu touch launcher
=> Do application reset on first store_or_update

scripts/container-manager.sh, src/anbox/cmds/container_manager.cpp, src/anbox/cmds/container_manager.h, src/anbox/container/lxc_container.cpp, src/anbox/container/lxc_container.h, src/anbox/container/service.cpp, src/anbox/container/service.h
In some spare situations it might be useful to change the network
configuration of the bridge and with that also the configuration of
the Android container itself. We don't validate the configuration
and just apply it no matter if it ends up with network connectivity
in the container.
Fixes #840 #839
Documentation can be found at https://docs.anbox.io/userguide/advanced/network_configuration.html
=> cmds: allow users to change the container network configuration

src/anbox/cmds/check_features.cpp
=> cmds: add override for Intel Core i5 M 460

CMakeLists.txt, external/cpu_features/CMakeLists.txt, src/anbox/cmds/check_features.cpp, src/anbox/dbus/bus.cpp, src/anbox/dbus/bus.h, src/anbox/dbus/stub/application_manager.cpp, src/anbox/graphics/emugl/RenderApi.cpp
This PR fixes two clang build errors. There are still three left but I was unsure how they should be handled since they are warnings for unused variables and i am not familiar with anbox codebase so i can not tell if they are false positives or not.
```
src/anbox/cmds/check_features.cpp:41:11: error: lambda capture 'this' is not used [-Wunused-lambda-capture]
action([this](const cli::Command::Context&) {
^
…
src/anbox/dbus/bus.h:51:8: error: private field 'type_' is not used [-Wunused-private-field]
Type type_;
^
…
/home/raetiacorvus/Documents/aur/anbox-git/src/anbox/src/anbox/graphics/emugl/RenderApi.cpp:33:23: error: unused variable 'default_glesv1_lib' [-Werror,-Wunused-const-variable]
constexpr const char *default_glesv1_lib{"libGLESv1_CM.so.1"};
^
```
=> Fix clang build errors

.github/stale.yml
We want to get issues without activity closed after a while unless they
are marked with specific labels to keep things clean and maintainable.
=> Add probot stale configuration

src/anbox/cmds/check_features.cpp
I am also getting the same SSE error while downloading through `snap install` on a virtual machine with an Intel Xeon Processor:
> The CPU of your computer (Intel(R) Xeon(R) CPU E5520 @ 2.27GHz) does not support all
> features Anbox requires.
> It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3
but checking `/proc/cpuinfo` reveals that it supports the features:
> ...
> model name	: Intel(R) Xeon(R) CPU E5520 @ 2.27GHz
> ...
> flags	: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni **_ssse3 sse4_1 sse4_2_** x2apic hypervisor lahf_lm pti
I hope adding the following code into the array in `check_features.cpp` could fix the problem:
> // …
=> Update check_features.cpp - Added override for Intel Xeon E5520

src/anbox/cmds/check_features.cpp
`snap install` complains
> The CPU of your computer (Intel(R) Core(TM) i7 CPU       Q 720  @ 1.60GHz) does not support all
features Anbox requires.
> It is missing support for the following features: SSE 4.1, SSE 4.2, SSSE 3...
but in `/proc/cpuinfo` 
> ...
> model name	: Intel(R) Core(TM) i7 CPU       Q 720  @ 1.60GHz
> ...
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida
=> Update check_features.cpp - Added override for Core i7-720QM

src/anbox/cmds/check_features.cpp, src/anbox/cmds/check_features.h
To prevent our whilelist from growing much more we know do an additional
sanity check via compiler builtin functions if we cannot detect all
mandatory CPU features via the cpu_features libray and if the CPU isn't
whitelisted. This should cover more or less all remaining cases unless
the compiler is unable to detect the features properly.
=> cmds: implement CPU feature sanity check via builtin compiler functions

cmake/FindGMock.cmake
Starting with googletest 1.8.1, I meet the following error when building
the tests.
```
/usr/bin/ld: ../../../gmock/libgmock_main.a(gmock_main.cc.o): in function `main':
/usr/src/googletest/googlemock/src/gmock_main.cc:52: undefined reference to `testing::InitGoogleMock(int*, char**)'
```
With this patch, I can build it successfully.
Build log: https://buildd.debian.org/status/logs.php?pkg=anbox&arch=amd64
=> cmake: link gtest_main to gmock lib

src/anbox/dbus/stub/application_manager.cpp
The expected C type of a sd-bus boolean is int and not boolean.
This fixes a possible stack smashing caused by the varying types.
See https://github.com/libratbag/libratbag/issues/433 which had the same
problem.
=> dbus: fix stack smashing

src/anbox/platform/sdl/platform.cpp, src/anbox/platform/sdl/platform.h
before of SDL 2.0.7 on X11 tfinger coordinates are not normalized, Ubuntu 16.04 use SDL 2.0.4, starting from SDL 2.0.7, SDL normalize the tfinger coordinates in the private fuction xinput2_normalize_touch_coordinates.
The second commit point out that windowID is not a field of SDL_TouchFingerEvent event, and window is always NULL for touch events, so set windowID when the window is created or when the window take input focus
=> Touch on linux, some fixes

android/opengl/system/gralloc/gralloc.cpp
Hi,
I am not absolutely sure about this, but the constants cause discrapancies in buffer sizes, which makes osmand (https://f-droid.org/en/packages/net.osmand.plus/) crash at start. With this change osmand runs correctly.
Pavel
=> do not use constants for glFormat and glType

external/android-emugl/host/libs/CMakeLists.txt, external/android-emugl/host/libs/GLESv1_dec/CMakeLists.txt, external/android-emugl/host/libs/GLESv2_dec/CMakeLists.txt, external/android-emugl/host/libs/libOpenGLESDispatch/CMakeLists.txt, external/android-emugl/host/libs/renderControl_dec/CMakeLists.txt
Some improvements to the build system which for example allows you to rerun make after a successful build without causing rebuild of the generated sources and libraries and programs that use them.
=> emugl: rebuild generated sources only when needed

src/anbox/container/lxc_container.cpp
Use the custom gateway if present and extend the configuration option
container.network.address to allow both an IPv4 address and a prefix
length, or only an IPv4 address in which case the prefix length is set
to 24. Which means the following configuration options give the same
result.
snap set anbox container.network.address=192.168.250.2/24
snap set anbox container.network.address=192.168.250.2
Closes #1052
=> container: fix container gateway and address prefix length

scripts/snap-wrapper.sh
"libEGL warning: FIXME: egl/x11 doesn't support front buffer rendering." floods logs otherwise
#1092 #861
=> Suppress EGL warning spam

.github/ISSUE_TEMPLATE.md
`anbox system-info` usually spans a screen or two, which can be mighty annoying when scrolling down to comments
=> Use collapsible section for system-info output in issue template

src/anbox/dbus/sd_bus_helpers.h
Use pre-defined macros to fill the systemd structures,
whose uninitialized field might otherwise
cause undefined behavior, as stated in the systemd header.
=> repair build on GCC 8.3.0

src/anbox/dbus/sd_bus_helpers.h
Reverts anbox/anbox#1137
Breaks with gcc 5.3 on Ubuntu 16.04 which is our primary delivery channel via snaps.
=> Revert "repair build on GCC 8.3.0"

src/CMakeLists.txt, src/anbox/dbus/sd_bus_helpers.c, src/anbox/dbus/sd_bus_helpers.hpp, src/anbox/dbus/skeleton/application_manager.cpp
This fixes the missing-field-initializers warning
and maintains compatibility with the C++ standard
(which pull request #1137 did not), thus working
also with older compilers that lack C struct initialization.
=> fix(anbox#1153): compile dbus helpers in C

src/anbox/common/binary_writer.cpp
With newer boost 1.71.0 with:
https://github.com/boostorg/endian/commit/6b5792647c5c2ffb4a375c9e1dc065e73f324f49#diff-5a08a00b5b1ec741b8b13cf3c1396874
boost/endian/conversion.hpp isn't included by
boost/endian/buffers.hpp and the build fails with:
src/anbox/common/binary_writer.cpp: In member function 'void anbox::common::BinaryWriter::write_uint16(uint16_t)':
src/anbox/common/binary_writer.cpp:52:24: error: 'native_to_big' is not a member of 'boost::endian'
52 |     v = boost::endian::native_to_big(value);
|                        ^~~~~~~~~~~~~
src/anbox/common/binary_writer.cpp:55:24: error: 'native_to_little' is not a member of 'boost::endian'
55 |     v = boost::endian::native_to_little(value);
|                        ^~~~~~~~~~~~~~~~
src/anbox/common/binary_writer.cpp: In member …
=> binary_writer.cpp: fix compatibility with boost-1.71.0

src/anbox/daemon.cpp
A trivial patch to remove the confused message when people just
type "anbox" in their terminal.
```
$ anbox
Unknown command 'run'
NAME:
anbox - anbox
...
```
=> set default argv to help

src/anbox/cmds/check_features.cpp, src/anbox/cmds/system_info.cpp
It breaks build on Alpine/postmarketOS, and is explicitely an error on more recent version of cpu_features: https://github.com/google/cpu_features/blob/master/include/cpuinfo_x86.h#L207.
protecting the include with `#ifdef` fix the problem, as every use of cpu_features is already protected.
=> fix arm build: avoid including x86-only header from cpu_features on arm

src/anbox/platform/sdl/window.cpp
it is annoying when you want to drag something near the edge, and then the window is resized.
- do not resize or drag when window is fullscreen
- do not resize when window is maximized
- do not check button area in single window mode
- use thinner drag area in single window mode
set `window_resize_border` to 10 or less might be better
=> platform/sdl: improve user experience when resize window

src/anbox/platform/sdl/window.cpp
When user close window by DE's dock or keyboard shortcut (for example, ALT-F4). The window will be closed twice.
And session-manager will print a warning like:
```
Got window removed event for unknown window (id 0)
```
The `close()` do the same things as `if (observer_) observer_->window_deleted(id_);`
This patch will fixup this.
=> platform/sdl: fixup window double-closed in SDL_WINDOWEVENT_CLOSE

scripts/create-package.sh
This change allows having a source dir that is readonly. For example calling the script as such: `scripts/create-package.sh ../../out/target/product/$ARCH/ramdisk.img ../../out/target/product/$ARCH/system.img ../../out/android.img`.
One often wants to use a read only source dir when building from a container or in pmOS' case, from a chroot.
This change is backward compatible.
=> create-package.sh: add optional third argument for output

docs/build-android.md
If I'm not mistaken, the path was incorrect. The anbox dir is apparently in /vendor.
=> fix script path in doc/build-android.md

src/anbox/input/device.cpp, src/anbox/input/manager.cpp
The input sockets are created within the user tmpfs (e.g. /run/user/...).
Files/sockets created there might not be accessible to other users.
Since the input sockets are bind-mounted into the Android container,
it will crash with "Permission denied" when it is unable to access them.
Make sure to give the created directory+socket files appropriate
permissions so they can be accessed within the Android container.
Similar code exists for the `anbox_bridge` and `anbox_audio` socket:
https://github.com/anbox/anbox/blob/3ed2e6d5c360d57b6aa61386e279adf3ff155ded/src/anbox/container/service.cpp#L54-L55
https://github.com/anbox/anbox/blob/3ed2e6d5c360d57b6aa61386e279adf3ff155ded/src/anbox/audio/server.cpp#L59-L61
Fixes #603.
Cc: @necessarily-equal
=> input: Ensure sockets are accessible from within the container

docs/install.md
On some Ubuntu-based systems (Elementary OS) PPAs are disabled by default.
The package `software-properties-common` needs to be manually installed.
=> Add instruction to enable PPAs

src/anbox/cmds/container_manager.cpp, src/anbox/cmds/container_manager.h
`anbox container-manager --force-squashfuse` enforces to use `squashfuse`.
This flag is useful for avoiding `anbox[70]: Could not create loopback device: No such file or directory` error that happens when running Anbox inside Docker : https://github.com/aind-containers/aind/issues/5
=> container-manager: support setting --force-squashfuse

products/armv7-a-neon/BoardConfig.mk
This backport two fixes by @Minecrell used in the postmarketOS Anbox image for armv7.
The first make the Anbox image work on recent kernels, as 32bits binder support was dropped. The second is for consistency.
=> armv7 tweaks

README.md
`apt install python-minimal` will setup python 2.7
=> apt install python2 is deprecated

src/anbox/cli.cpp
This uniforms message of subcommand help to others description.
```
$ ./anbox help
NAME:
anbox - anbox
USAGE:
anbox [command options] [arguments...]
COMMANDS:
wait-ready                     Wait until the Android system has successfully booted                                               
help                           Print a short help message                                                                          
session-manager                Run the the anbox session manager                                                                   
launch                         Launch an Activity by sending an intent                                                             
check-features                 Check that the host system supports all necessary features …
```
=> typo: command help

scripts/snap-wrapper.sh, src/anbox/cmds/session_manager.cpp, src/anbox/cmds/session_manager.h, src/anbox/platform/base_platform.h, src/anbox/platform/sdl/platform.cpp, src/anbox/platform/sdl/window.cpp, src/anbox/platform/sdl/window.h
Add command line option `--server-side-decoration` and `ANBOX_FORCE_SERVER_SIDE_DECORATION` env-var for session-manager to use server-side decoration. Both methods can activate it.
When using server-side decoration, the hit test handler will NOT be set beacuse we don't need to simulate the behavior of the title bar and resize area.
Currently android framework layer will render caption (client-side decoration), in order to let the android framework layer know that sometimes we need server-side decoration. I introduce a special system property `ro.anbox.no_decorations`. When it is true, hide the android client-side decoration caption unconditionally. When server-side decoration is enabled, this property is set to `1`.
Therefore, server-side decoratio needs to be used with another pull …
=> session-manager: implement configurable server-side decoration

cmake/FindGMock.cmake
some distributions, at least Arch and Alpine, ship a binary package with
a pkg-config. On those platforms, tests are disabled or such a patch is applied.
I tested this to still build on Debian and Alpine. Arch should be unaffected.
=> use gtest in a sane way when it is packaged properly.

src/anbox/cmds/version.cpp
Follow up to https://github.com/anbox/anbox/pull/1442.
the first word of the `anbox version` description ("print the version of the daemon") had no capital, unlike the other help messages. This merge request fixes that.
=> make help message fully consistent

cmake/FindGMock.cmake
A few files, notably the testsuite, use the GTEST_BOTH_LIBRARIES. This
sets it on both code path and correct the mistake from earlier (#1423).
The Alpine package check caught it.
=> cmake/FindGMock: fixup b2accb4aa

snap/snapcraft.yaml
if the image isn't the right one, the build should *not* continue.
I tested that part of the script, so it should not break build.
=> snap: fail to build if image's checksums are wrong

src/anbox/container/lxc_container.cpp
closes https://github.com/anbox/anbox/issues/1436. It could not be the perfect solution, but I don't think it has potential for regressions.
`lxc.cap.drop` existed already in LXC1.0, so I assume this should be
backward compatible.
=> forbid android from waking up the host

src/anbox/rpc/message_processor.cpp
fixes a error where the message
```
[platform_message_processor.cpp:46@process_event_sequence] Failed to parse events from raw string
```
is followed by a crash at `../src/anbox/rpc/message_processor.cpp:81`.
since buffer_.size() is signed, it could underflow and the safety would
not trigger, leading to a crash.
credits to mntmn for finding the bug and the solution.
=> message_processor.cpp: fix underflow error

snap/.snapcraft/state, snap/snapcraft.yaml
Newer swiftshader fails to build on 16.04 due to the user of features of
newer cmake versions.
=> snap: use older swiftshader version

docs/install.md
wording taken from https://github.com/anbox/anbox-modules/issues/20#issuecomment-570204411 @morphis comment
ref #20 #1309 #1240
=> Update docs for unable to access '/ dev / binder'

snap/snapcraft.yaml
This upgrades the snap to the 20.04 version. @tomasz-grobelny figured out the second part, cheers!
@morphis: before merging this, maybe we could fix some inconsistency. The `snapcraft.yaml` contains `grade: devel`, but also contains the `snapcraftctl set-grade stable` command. Which should we keep?
=> 20.04 snap

snap/snapcraft.yaml
the snap contains `grade: devel` at the top already
=> snap: cleanup devel/stable ambiguity

scripts/build-with-docker.sh
When compiling in a container the system user root is owning all of the produced artifacts.
Moving and removing build artifacts was not possible without elevation.
The script was modified to use the current system user and group id instead.
=> Use current system user and group in docker build script

docs/build-android.md
Also, add a hint that the path will be slightly different for each target architecture.
=> README: Fix image paths after /anbox -> /vendor/anbox change

src/anbox/platform/sdl/platform.cpp
SDL 2.0.10 introduced mouse event emulation for touch input.
However, Anbox already handles touch events by itself, so this just
results in duplicated events and erroneous input when using Anbox
with a touch screen (for instance, on the Librem 5).
Signed-off-by: Sebastian Krzyszkowiak <sebastian.krzyszkowiak@puri.sm>
=> platform/sdl: Disable mouse event emulation for touch input

src/anbox/protobuf/anbox_bridge.proto, src/anbox/protobuf/anbox_container.proto, src/anbox/protobuf/anbox_rpc.proto
Added version hints to protobuf files, so libprotobuf stops complaining:
```
[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: anbox_container.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: anbox_bridge.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: anbox_rpc.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
```
=> Use proto2 syntax

src/anbox/container/management_api_skeleton.cpp, src/anbox/container/management_api_skeleton.h, src/anbox/container/service.cpp
PendingCallCache was a ctor param of ManagementApiSkeleton, but was not used apart from setting the private member.
=> remove PendingCallCache from ManagementApiSkeleton

src/anbox/cmds/session_manager.cpp, src/anbox/rpc/connection_creator.cpp, src/anbox/rpc/connection_creator.h
`rpc::ConnectionCreator` has unused reference to `Runtime` as parameter
* remove parameter
=> remove unused parameter Runtime

src/CMakeLists.txt, src/anbox/graphics/opengles_message_processor.cpp, src/anbox/graphics/opengles_message_processor.h, src/anbox/graphics/opengles_socket_connection.cpp, src/anbox/graphics/opengles_socket_connection.h, src/anbox/network/base_socket_messenger.cpp, src/anbox/network/message_processor.h, src/anbox/network/socket_connection.h, src/anbox/qemu/pipe_connection_creator.cpp
This removes unnecessary std::copy
For the amount these functions get called, std copy is way to expensive
to do. This removes the need for buffer to be copied twice, first to a
std::vector then SmallFixedVector. This also directly copies buffer into
a smallVector without the init overhead smallVector's ctor does. This
result is a massive performance boost (at least on arm devices).
Also use memcpy interestingly seems to be faster on arm
devices, on amd64 they seems to be about the same speed.
Same as https://github.com/anbox/anbox/pull/902 but 2 years late :)
=> Improve performance

src/anbox/container/lxc_container.cpp
Uses bindtab file in anbox data directory to bind directory from host to anbox container.
Resolve #1754.
=> Add host directory bind mount support in anbox.

external/CMakeLists.txt
We found that, when packaging anbox for Arch Linux (https://aur.archlinux.org/packages/anbox-git/), it conflicts with another package (libvolk). This is because both packages ship with cpu_features.
It is completely unnecessary to have cpu_features installed for Anbox to work, since it is a static library and is already linked into Anbox anyway.
Therefore, this pull requests disables installation of cpu_features on `make install`.
=> Do not install cpu_features on make install

README.md, docs/install.md
It's old, and basically only works with linux 5.4 lts. People come really often asking for support for that, while it's not the issue at hand.
=> Update installation instructions to drop anbox-modules mentions

src/anbox/cmds/system_info.cpp
See commit for more details :
https://github.com/anbox/anbox/commit/92286b81bbcd6b51f1ebce3a4626a0ec6b21e8c4
=> cmds: add binderfs support to system information output

external/xdg/xdg.h, src/anbox/common/mount_entry.h, src/anbox/input/manager.h
* fixes:
anbox/3.0+gitAUTOINC+9de4e87cdd-r0/git/src/anbox/common/mount_entry.cpp:25:29: error: no declaration matches 'std::shared_ptr<anbox::common::MountEntry> anbox::common::MountEntry::create(const boost::filesystem::path&, const boost::filesystem::path&, const string&, long unsigned int, const string&)'
anbox/3.0+gitAUTOINC+9de4e87cdd-r0/git/src/anbox/common/mount_entry.cpp:47:29: error: no declaration matches 'std::shared_ptr<anbox::common::MountEntry> anbox::common::MountEntry::create(const std::shared_ptr<anbox::common::LoopDevice>&, const boost::filesystem::path&, const string&, long unsigned int, const string&)'
anbox/3.0+gitAUTOINC+9de4e87cdd-r0/git/src/anbox/common/mount_entry.cpp:57:29: error: no declaration matches 'std::shared_ptr<anbox::common::MountEntry> …
=> Fix build with glibc-2.34 and gcc-11

scripts/anbox-bridge.sh
The comments instruct systemd on the correct boot order for anbox-bridge.sh
=> Compatibility for anbox-bridge.sh with systemd.generator
