- README.md
> Fixed design links.

- scripts/container-manager.sh
> Check for AppArmor support before using aa-exec

- data/anbox.service.in
- debian/control
- debian/rules
> Ensure anbox can be properly started by a systemd --user instance

- src/anbox/graphics/emugl/RenderControl.cpp
- tests/anbox/graphics/CMakeLists.txt
- tests/anbox/graphics/render_control_tests.cpp
Fixes https://github.com/anbox/anbox/issues/287
> Correct screen dimensions

- snapcraft.yaml
* Don't crash inside AlarmManager when PendingIntent is not set
Fixes #353
> Update android image

- CMakeLists.txt
- cmake_uninstall.cmake.in
> added uninstall target to cmake to allow make uninstall operation

- kernel/99-anbox.rules
- kernel/binder/binder.c
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
> binder: use own major

- src/anbox/graphics/emugl/Renderer.cpp
fix this problem: "GLM: GLM_GTX_transform is an experimental extension and may change in the future"
> fix GLM error

- src/CMakeLists.txt
This makes them all visible in any IDEs supporting cmake.
> Add missing source files to cmake build configuration

- scripts/container-manager.sh
- src/anbox/cli.h
- src/anbox/cmds/container_manager.cpp
- src/anbox/cmds/container_manager.h
- src/anbox/common/mount_entry.cpp
- src/anbox/container/lxc_container.cpp
- src/anbox/container/lxc_container.h
- src/anbox/container/service.cpp
- src/anbox/container/service.h
- src/anbox/system_configuration.cpp
- src/anbox/system_configuration.h
This will allow users to extend the Android root filesystem with
additional system applications and changes.
> Add support for an overlayed Android root filesystem

- scripts/container-manager.sh
> scripts: set explicit search path for libboost_log

- CMakeLists.txt
- src/anbox/platform/sdl/window.cpp
This adds option to disable wayland
> Add option to enable/disable wayland

- src/anbox/application/launcher_storage.cpp
- src/anbox/application/launcher_storage.h
- src/anbox/system_configuration.cpp
This makes anbox place applications in the main application folder
This is mostly a hack for ubuntu touch
> Add ANBOX_NO_DESKTOP_SUBDIR env

- src/anbox/cmds/check_features.cpp
Not all CPUs can be detected with their correct feature set. For example
does cpu_features not work well enough when the support does not support
AVX (see https://github.com/google/cpu_features/issues/4). To mitigate
this we maintain a list of whitelisted CPU models.
Fixes #859
> cmds: add cpu whitelist for features check

- CMakeLists.txt
This changes the options to mach the ENABLE_* format
> Change options to match ENABLE_* format

- src/anbox/cmds/check_features.cpp
> cmds: add override for Intel Celeron N2840

- src/anbox/platform/sdl/platform.cpp
- src/anbox/ui/splash_screen.cpp
> Hint SDL to not disable compositing

- external/process-cpp-minimal/src/core/posix/signal.cpp
- src/anbox/container/lxc_container.cpp
- src/anbox/logger.cpp
These changes are needed to compile Anbox with the musl libc. I heard there was an interest in upstreaming patches, so here's some!
> musl fixes

- src/anbox/graphics/buffer_queue.cpp
- src/anbox/graphics/buffer_queue.h
Remove unused method `wait_until_not_empty_locked`
Signed-off-by: keyangxie <keyang.xie@gmail.com>
> remove unused function

- docs/runtime-setup.md
added link to download prebuilt android images
> extended runtime-setup doc

- scripts/container-manager.sh
- snap/snapcraft.yaml
This also modernize the snap a bit.
Note that this removes the snap desktop integration. I'm not sure if it was used by anything.
> snap: upgrade snap to 18.04

- docs/install.md
Update documentation following https://github.com/anbox/anbox/issues/1579 and https://github.com/anbox/anbox/issues/1570. Thanks @GizmoChicken for the help!
> Update instructions for Ubuntu 20.04

- README.md
- src/CMakeLists.txt
- src/anbox/application/gps_info_broker.h
- src/anbox/cmds/session_manager.cpp
- src/anbox/dbus/gps.xml
- src/anbox/dbus/gps_server.cpp
- src/anbox/dbus/gps_server.h
- src/anbox/qemu/gps_message_processor.cpp
- src/anbox/qemu/gps_message_processor.h
- src/anbox/qemu/pipe_connection_creator.cpp
- src/anbox/qemu/pipe_connection_creator.h
Tested to work on data generated from https://nmeagen.org/ and OsmAnd. Ready for review (@morphis, @necessarily-equal).
> Allow injecting GPS location via DBus calls

- .github/workflows/main.yml
- .travis.yml
aftermath of https://github.com/anbox/anbox/pull/1618
add --clean to build script calls
> restore travis and Github CI behavior

- data/desktop/anbox-android.menu
- data/desktop/android-settings.desktop
- src/anbox/application/launcher_storage.cpp
> Add xdg menu category for anbox apps

- src/anbox/container/lxc_container.cpp
fixes https://github.com/anbox/anbox/issues/462
> add config item: lxc.prlimit.nice

- src/anbox/utils.cpp
Better to do break out of while loop.
> Do break out of while loop

- data/desktop/anbox-android.directory
I forgot to include the directory file in previous pr #1639 :3﻿
> xdg desktop directory for anbox category
